version: "3.9"

services:
  fuseki:
    image: stain/jena-fuseki
    container_name: fuseki-server
    ports:
      - "3030:3030"
    environment:
      - FUSEKI_HOME=/fuseki
      - ADMIN_PASSWORD=${FUSEKI_PASSWORD} # Admin password from .env file
    volumes:
      - ../@mm.ttl:/fuseki/@mm.ttl
      - ./data:/fuseki/databases # Persist data
      - ./shiro.ini:/fuseki/shiro.ini
      - ./config:/fuseki/config # Mount configuration files
    entrypoint:
      - java
      - -jar
      - fuseki-server.jar
      - --config=/fuseki/config/assembler.ttl # Point to custom assembler
    restart: unless-stopped
